# Generated by Django 5.0.7 on 2024-07-30 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='api.flat')),
            ],
        ),
    ]
